### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by jesslam948** [adhithiganesan/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [ ] All relevant code examples written with backticks (```)
  - Any commands (such as `ls`, `ssh`, etc.) should be written within backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [ ] Lab report is on its own page, not the index page
  - Please link to your lab report on your [index page](https://adhithiganesan.github.io/cse15l-lab-reports)
- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
On **Gradescope**, when we ask for a *GitHub Pages* link, we want it to be the one that links to your website, not to the file in the GitHub repo! For example, for the lab report, you should give us:
https://adhithiganesan.github.io/cse15l-lab-reports/lab-report-1-week-2

Otherwise, good job!
![image](https://user-images.githubusercontent.com/22829218/163322433-acb684fe-ec27-4924-8ca4-e0a10635bae6.png)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by adhithiganesan** [comment]
Thank you for the feedback!
